### PR TITLE
add ghc9 support for polysemy-plugin

### PR DESCRIPTION
**Pull request by funketh**
Wasn't sure which branch to merge into since #410 is already open.
I think that if this PR is merged we can just merge ghc9 into master.

### CODE REVIEW

**Comment by tek** [comment]
awesome! I think we can also just merge this PR into the other

**Comment by KingoftheHomeless** [comment]
@tek Nix check failed twice. The logs aren't specific enough to detail what specific test goes awry. Since you work with Nix, could you figure it out? If it's just the usual suspect (`doctest` intermittently failing) then we can ignore it.

**Comment by funketh** [comment]
I don't use flakes yet so I can't comment on nix specific stuff but when I ran stack test it crashed while compiling the tests without giving any info (even in verbose mode)

**Comment by tek** [comment]
yeah I forgot to add the flag to `nix flake check` that enables full output. added it now on master

**Comment by tek** [comment]
tests seem to run fine on my machine :shrug:

**Comment by tek** [comment]
rebased with my branch on master, we'll see what GA has to say now

**Comment by tek** [comment]
oh wait I didn't run it for ghc 9 :sweat_smile:

**Comment by tek** [comment]
```
polysemy-plugin> test/TypeErrors.hs:17: failure in expression `:{       
polysemy-plugin>  existsKV :: Member (State (Maybe Int)) r => Sem r Bool                                     
polysemy-plugin>  existsKV = isJust get                                                                      
polysemy-plugin> :}'                                  
polysemy-plugin> expected: ...                                                                               
polysemy-plugin>           ... Couldn't match expected type ...Sem r Bool... with actual type ...Bool...                
polysemy-plugin>           ...                                                                               
polysemy-plugin>           ... Couldn't match expected type ...Maybe a0...
polysemy-plugin>           ... with actual type ...Sem r0 s0...                                                         
polysemy-plugin>           ...                                                                               
polysemy-plugin>  but got:                                                                                   
polysemy-plugin>           <interactive>:49:13: error:                                            
polysemy-plugin>               • Couldn't match expected type ‘Sem r Bool’ with actual type ‘Bool’
polysemy-plugin>               • In the expression: isJust get                       
polysemy-plugin>                 In an equation for ‘existsKV’: existsKV = isJust get
polysemy-plugin>               • Relevant bindings include                             
polysemy-plugin>                   existsKV :: Sem r Bool (bound at <interactive>:49:2)
polysemy-plugin>           <interactive>:49:20: error:                 
polysemy-plugin>               • Couldn't match expected type: Maybe a0
polysemy-plugin>           ..... Couldn't match expected type^          
polysemy-plugin>                             with actual type: Sem r0 s0        
polysemy-plugin>               • In the first argument of ‘isJust’, namely ‘get’
polysemy-plugin>                 In the expression: isJust get                       
polysemy-plugin>                 In an equation for ‘existsKV’: existsKV = isJust get
```

**Comment by tek** [comment]
I don't know how that `...` stuff works, I would guess that it just ensures that the substrings are present. In that case, it looks like it should pass? :shrug:

**Comment by tek** [comment]
got it, it's the spaces after `type`!

**Comment by KingoftheHomeless** [comment]
Huh. Did GHC 9 change error message formatting, or was this bug _always_ present?

**Comment by tek** [comment]
given that there's a duplicate `Couldn't match expected type` there that seems unfamiliar I assume that this is new

**Pull request merged**
