### PR TITLE
correct two switched INLINE pragmas

### PR DESCRIPTION
**Pull request by tek**
I assume this isn't some magic trick.

### CODE REVIEW

**Comment by googleson78** [comment]
These should actually work regardless of where they are placed, right?

**Comment by tek** [comment]
yes, it is purely cosmetic

**Review by TheMatten — APPROVED** [review]
Should be cosmetic, but I guess it makes a lot of sense from a clarity standpoint :D

**Comment by tek** [comment]
my thoughts exactly :smiley_cat:

**Pull request merged**
