### PR TITLE
Fix GHC 810 rc1 build

### PR DESCRIPTION
**Pull request by Avi-D-coder**
Test dependencies do not build.

### CODE REVIEW

**Comment by isovector** [comment]
What's the state of this?

**Comment by Avi-D-coder** [comment]
no idea. haven't checked if any of the test deps are upgraded to 8.10

**Comment by Avi-D-coder** [comment]
no idea. haven't checked if any of the test deps are upgraded to 8.10

**Comment by googleson78** [comment]
How do you build from this branch?
Running
```
git clean -fdx
stack build --stack-yaml stack810.yaml
```
results in a lot of stuff like this
```
Warning: Failed to decode module interface: /home/googleson78/git/polysemy/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0/build/Polysemy/Internal/Writer.hi Decoding failure:
         Invalid magic: e49ceb0f
```

**Comment by Avi-D-coder** [comment]
@googleson78 See https://github.com/commercialhaskell/stack/issues/5134

**Comment by sorki** [comment]
FWIW to build on NixOS I've only had to use https://github.com/polysemy-research/loopbreaker/pull/11

**Comment by TheMatten** [comment]
Is this PR still relevant? Because polysemy builds for me on current nightly snapshot (8.10.1) just fine, except for `dump-core` flag (but that seems to be upstream issue).

**Pull request closed without merging**
