### PR TITLE
Add `state` action to `State`

### PR DESCRIPTION
**Pull request by TheMatten**
Similar function can be found e.g. in `transformers` - but this one follows swapped order of elements in tuple already present in `polysemy`'s functions (like `runState` or `stateful`).

- [ ] Should we test it?

### CODE REVIEW

**Comment by isovector** [comment]
I'd prefer not to do this; now everyone will need to handle it in their interpreters, and it doesn't buy us anything semantically.

**Comment by TheMatten** [comment]
Turns out I don't actually want to use it in specific places as I thought previously - okay, let's close it for now then.

**Comment by KingoftheHomeless** [comment]
A `state` action actually _does_ buy us something semantically new: atomic modification.

**Comment by TheMatten** [comment]
@KingoftheHomeless Hmm, it's a nice property to carry in types - what about having:
```
data Atomic s m a where
  Atomic :: (s -> (s, a)) -> Atomic s m a
```
separately - and then we could have:
```
runStateAtomic :: Member (Atomic s) r => Sem (State s : r) a -> Sem r a
runStateAtomic = interpret $ \case
  Get   -> atomic $ \s -> (s, s)
  Put s -> atomic $ const (s, ())
```
to provide `get` and `put` over same state if needed.

**Comment by TheMatten** [comment]
@isovector What do you think about adding `Atomic` to zoo?

**Comment by KingoftheHomeless** [comment]
I'd probably call it `AtomicState`, and the action `atomicModify`.

The seperation between `State` and `AtomicState` is somewhat unfortunate if you want my opinion. I'd prefer if it were up to the interpreter, but the breakage of adding `state` to `State` would most likely be significant.

**Comment by ocharles** [comment]
In my work I have an effect 'Atomic m', which shows how to atomically embed any 'm a' into another monad. So in this, you'd have Atomic (Sem [State s])

**Comment by TheMatten** [comment]
@ocharles sound cool! I'm just worried it would be a little bit of an overkill in this case :smile:

**Pull request closed without merging**
