### PR TITLE
Move KVStore from polysemy-zoo to polysemy

### PR DESCRIPTION
**Pull request by locallycompact**
Hi. I'd like to move KVStore into the main repository. I find this very useful and use it quite heavily.

### CODE REVIEW

**Comment by tek** [comment]
notably, it has no dependencies

**Comment by googleson78** [comment]
Any opposition to this? @TheMatten @KingoftheHomeless 

It seems a bit too specific/non-traditional when compared with the other effects, but if people are often using it, I'm fine with including it.

Another idea is having a `polysemy-extra`, that has stuff such as this, but without the huge amount of dependencies that the zoo has (or perhaps just splitting the zoo so that it doesn't depend on `random`, `streaming`, etc)

**Comment by thma** [comment]
I always write a KVStore from scratch to avoid the dependencies of polysemy-zoo.

So I think it's a useful addition to polysemy.

**Comment by tek** [comment]
> Another idea is having a `polysemy-extra`, that has stuff such as this, but without the huge amount of dependencies that the zoo has (or perhaps just splitting the zoo so that it doesn't depend on `random`, `streaming`, etc)

is good idea

**Comment by KingoftheHomeless** [comment]
`polysemy-extra` is something we've though about before, mainly for moving stuff from `polysemy-zoo`.
I agree; there's sufficient reason to add it. It doesn't have to start big; we can begin by porting the obvious useful effects like `KVStore` and `Fresh`, and go from there.

**Comment by locallycompact** [comment]
I actually snagged that package name last week for my own nefarious purposes but I'm happy to migrate it here and share the love. http://hackage.haskell.org/package/polysemy-extra

**Comment by tek** [comment]
hackage squatter!!

**Comment by locallycompact** [comment]
I published kvstore under its own package here and updated polysemy-extra to depend on it and not the zoo.

https://hackage.haskell.org/package/polysemy-kvstore-0.1.2.0

**Comment by isovector** [comment]
I'm quite open to this change! But this PR is empty and old, so I'm going to close it. Feel free to reopen!

**Pull request closed without merging**
