### PR TITLE
Update outputToTrace definition

### PR DESCRIPTION
**Pull request by juanpaucar**
Solves #286

### CODE REVIEW

**Comment by KingoftheHomeless** [comment]
Could you update the documentation too? E.g. `Transforms an @'Output' w@ effect into a 'Trace' effect given a function to transform each @w@ to a 'String'.`

**Comment by juanpaucar** [comment]
@KingoftheHomeless Sorry about that, I totally forgot about updating the documentation. I just pushed the updated documentation too

**Comment by KingoftheHomeless** [comment]
Thanks!

**Comment by isovector** [comment]
I think this should have an explicit `forall w r a.` on it, so that you can type apply the effect; for example, today you'd need to write `outputToTrace @_ @MyEffect show`, when instead we could make it `outputToTrace @MyEffect show`

**Comment by juanpaucar** [comment]
Hi @isovector, Would this change be enough? https://github.com/juanpaucar/polysemy/commit/68307b671139bcf74fa74ef51fddf4fb4a3b1605

I  think I will need to open another PR for that if you want it

**Comment by isovector** [comment]
Yup, that would be enough!

**Pull request merged**
