### PR TITLE
Add inlining to Polysemy.Writer

### PR DESCRIPTION
**Pull request by KingoftheHomeless**
I forgot to add those wacky `INLINE` pragmas...

### CODE REVIEW

**Comment by isovector** [comment]
I wonder if we could convince `Loopbreaker` to insert these automatically. @TheMatten any ideas?

**Comment by TheMatten** [comment]
You mean something like `INLINE` to all functions that manipulate `Sem` type, or all functions in module?

**Comment by isovector** [comment]
Just things that are wrappers around `send`.

**Comment by isovector** [comment]
I think it's a good idea to manually mark your interpreters as `INLINE`, but the actions should technically be `INLINEABLE CONLIKE`, which is more of a mouthful than I want to ask from users. The TH correctly generates the right stuff.

**Comment by TheMatten** [comment]
Generally (and this should be compatible with reimplementation in the future), I would like to have `{-# ANN foo Loopbreaker #-}`, that would just "do it's magic" and add required annotations and stuff.

**Pull request merged**
