### PR TITLE
Add fromException and fromExceptionVia

### PR DESCRIPTION
**Pull request by isovector**
Been thinking about how to write good real life code with polysemy --- realized this thing was conspicuously missing.

### CODE REVIEW

**Comment by KingoftheHomeless** [comment]
Should we provide a `Final`-generalized variant too?

```haskell
fromExceptionSemVia
    :: ( X.Exception exc
       , Member (Error err) r
       , Member (Final IO) r
       )
    => (exc -> err)
    -> Sem r a
    -> Sem r a
fromExceptionFinalVia f m = do
  r <- withStrategicToFinal $ do
    m' <- runS m
    s  <- getInitialStateS
    pure $ (fmap . fmap) Right m' `X.catch` \e -> pure (Left e <$ s)
  case r of
    Left e -> throw $ f e
    Right a -> pure a
```

**Comment by isovector** [comment]
I think if you're throwing exceptions in polysemy you deserve to get burned! Would `fromExceptionSemVia` buy us anything I'm not seeing?

**Comment by KingoftheHomeless** [comment]
@incertia [had a use-case where it would've been useful](https://github.com/polysemy-research/polysemy/issues/243#issue-503009538). Although from what I can tell, it was mostly for convenience; instead of doing `fromExceptionVia` on every IO action which may throw an exception, you instead apply `fromExceptionSemVia` on a big batch of actions converting any IO exception that may occur.

**Comment by isovector** [comment]
That sounds reasonable to me. I'd be happy to merge a PR.

**Pull request merged**
