### PR TITLE
Try to pass travis with 8.8.1

### PR DESCRIPTION
**Pull request by googleson78**
Am I doing this right?
(progress toward #235 (hopefully))

### CODE REVIEW

**Comment by isovector** [comment]
[And now we wait](https://travis-ci.org/polysemy-research/polysemy/jobs/599545192) and find out!

**Comment by googleson78** [comment]
```
[__1] trying: unagi-chan-0.4.1.2 (dependency of polysemy)
```
Why won't it use `unagi-chan-0.4.1.3` :thinking:

**Comment by googleson78** [comment]
Well.. the build is passing now, after the bump to cabal 3, but it seems the doctest that depends on the plugin is broken? Help?

**Comment by isovector** [comment]
I'm not sure offhand. I'll try digging in later today!

**Comment by googleson78** [comment]
I think `type-error` also needs a bump, currently looking into that.

**Comment by googleson78** [comment]
Ok, I think `doctest` is broken with `cabal 3.0`/`ghc 8.8.1`

**Comment by isovector** [comment]
If this is the only thing preventing 8.8.1, I'd be happy to CPP those tests out and we can figure out a solution later.

**Comment by googleson78** [comment]
Well I'm obviously just flailing about right now:

Entirely disabling the two doctests (by commenting them out!) work. I created an issue at `doctest` too - https://github.com/sol/doctest/issues/245

But then the `cabal install polysemy*.tar.gz` fails. Perhaps newer `cabal install` invocations don't support `.tar.gz`s?

**Comment by isovector** [comment]
Thanks for your work on this, @googleson78 . I just merged #267 which I think fixes it!

**Pull request closed without merging**
