### PR TITLE
Delete deprecated

### PR DESCRIPTION
**Pull request by isovector**
fuck deprecated code!!

### CODE REVIEW

**Comment by KingoftheHomeless** [comment]
`runFixpoint` should go too, right?

**Comment by isovector** [comment]
Yeah, it should, but the comment scared me about how we need the `runIdentity` bit afterwards.

**Comment by isovector** [comment]
Can we write a `runPure` with that is like the new `runM` in #239 , except specialised to `Identity`? Then this thing would just work?

**Comment by KingoftheHomeless** [comment]
We had a previous discussion about this when I did the `Final` rework at `polysemy-zoo`.
https://github.com/polysemy-research/polysemy-zoo/pull/45#discussion_r316719585

**Pull request closed without merging**
